<?php
$page_title = 'Academic Calendar - SSSUTMS';
$banner_title = 'Academic Calendar';
$banner_category = 'Academic';

require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/topbar.php';
require_once __DIR__ . '/../includes/navbar.php';
require_once __DIR__ . '/../includes/page-banner.php';
?>

<section class="subpage-main-section py-4 bg-light">
  <div class="container-fluid px-lg-5">
    <div class="row g-4 align-items-start">
      
      <!-- Main Content Area (Left) -->
      <div class="col-lg-8 col-xl-9">
        <div class="content-card">
          <div class="content-card-body">
            <p></p>
<p class="MsoNormal"></p>
<h2 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: center;" align="center"><span style="font-size: 12pt; color: #2dc26b;"><strong><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';"><span style="font-size: 14pt;"><span style="text-decoration: underline;"><span style="color: #e03e2d; font-size: 18pt; text-decoration: underline;">Academic Calendar for the Year 2026-27&nbsp; </span></span></span></span></span></strong></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/MBBS.pdf" target="_blank" rel="noopener"><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></a></h2>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center">&nbsp;</h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><img src="<?php echo BASE_URL; ?>assets/images/Files/Link/Arrow1_copy_06062026_0241.jpg"  height="18" /><span style="font-size: 12pt;"><strong><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;">&nbsp;<span style="font-family: 'comic sans ms', sans-serif;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/FIRST YEAR.pdf" target="_blank" rel="noopener">DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</a></span></span><span style="font-family: 'comic sans ms', sans-serif;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/FIRST YEAR.pdf" target="_blank" rel="noopener"><span style="color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase;">/BHMCT</span></a><span class="MsoHyperlink"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/FIRST YEAR.pdf" target="_blank" rel="noopener">(First Year)</a> </span></span></strong></span><span style="font-family: 'comic sans ms', sans-serif;"><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-family: 'comic sans ms', sans-serif;"><img src="<?php echo BASE_URL; ?>assets/images/Files/Link/Arrow1_copy_06062026_0241.jpg"  height="17" /><strong><span style="font-size: 14pt;"><span class="MsoHyperlink"><span style="line-height: 115%;">&nbsp;<a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/SECOND YEAR.pdf" target="_blank" rel="noopener"> </a></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/SECOND YEAR.pdf" target="_blank" rel="noopener"><span style="color: #241f2a; text-transform: uppercase;"><span style="font-size: 12pt;">DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span></span><span style="color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase; font-size: 12pt;">/BHMCT</span></a></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/SECOND YEAR.pdf" target="_blank" rel="noopener"><span class="MsoHyperlink"><span style="font-size: 12pt;">(Second Year) </span></span></a></strong><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-family: 'comic sans ms', sans-serif;"><img src="<?php echo BASE_URL; ?>assets/images/Files/Link/Arrow1_copy_06062026_0241.jpg"  height="17" /> <strong><span style="font-size: 14pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/third and forth year.pdf" target="_blank" rel="noopener"><span style="color: #241f2a; text-transform: uppercase;"><span style="font-size: 12pt;">DIPLOMA ENGG. (Third Year) /B. E./B. Pharma</span></span><span style="color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase; font-size: 12pt;">/BHMCT</span></a></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2026-27/third and forth year.pdf" target="_blank" rel="noopener"><span class="MsoHyperlink">(Third &amp; Fourth Year)&nbsp;</span></a></strong><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-family: 'comic sans ms', sans-serif;"><img src="<?php echo BASE_URL; ?>assets/images/Files/Link/Arrow1_copy_06062026_0241.jpg"  height="17" />&nbsp;</span><span style="font-size: 12pt;"><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/acadmic_clan_09072026_0139.pdf" target="_blank" rel="noopener"><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"><span style="font-family: 'comic sans ms', sans-serif;">UTD/EDUCATION/PHYSICAL EDUCATION/AGRICULTURE/LIBRARY SCIENCE </span></span></a><span style="font-family: 'comic sans ms', sans-serif;"><span class="MsoHyperlink"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/acadmic_clan_09072026_0139.pdf" target="_blank" rel="noopener">(2026-27)</a> </span></span></strong></span><span style="font-family: 'comic sans ms', sans-serif;"><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-family: 'comic sans ms', sans-serif;"><img src="<?php echo BASE_URL; ?>assets/images/Files/Link/Arrow1_copy_06062026_0241.jpg"  height="17" /> </span><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Comic Sans MS';   color: #241f2a; text-transform: uppercase; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/academic_calendar_09072026_0224.pdf" target="_blank" rel="noopener">Academic Calendar for the year 2026-27 (School of Law)</a>&nbsp;</span></strong><span style="font-family: 'comic sans ms', sans-serif;"><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center">&nbsp;</h3>

<h2 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: center;" align="center"><span style="font-size: 12pt; color: #2dc26b;"><strong><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';"><span style="font-size: 14pt;"><span style="text-decoration: underline;"><span style="color: #e03e2d; font-size: 18pt; text-decoration: underline;">Academic Calendar for the Year 2025-26&nbsp; </span></span></span></span></span></strong></span></h2>

<h3 class="MsoNormal" style="text-align: left;"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Adobe_Scan_19_Aug_2025_(1)_21082025_1254.pdf" target="_blank" rel="noopener"><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;">Academic Calendar for the year 2025-2026 B.A.B.Ed /B.Ed/B.P.Ed&nbsp;</span></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Adobe_Scan_19_Aug_2025_21082025_1256.pdf" target="_blank" rel="noopener"><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"><span lang="EN-US">ACADEMIC CALENDAR FOR I &amp; II YEAR 2025-26&nbsp;</span> <span lang="EN-US" style="line-height: 115%;">FOR D.PHARMA </span></span></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/bpes1-3_23082025_0420.pdf" target="_blank" rel="noopener">Academic Calendar for the year 2025-26 for B.P.E.S PROGRAMME I ,II &amp; III Year</a>&nbsp;</h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Adobe_Scan_21_Aug_2025_(2)_23082025_0422.pdf" target="_blank" rel="noopener"><strong style="box-sizing: border-box; font-weight: bold;">Academic Calendar for the year 2025-26 (School of Law)&nbsp;</strong></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IMG_29092025_1027.pdf" target="_blank" rel="noopener"><span style="font-size: 12pt;"><strong><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"> DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span><span style="font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase;">/BHMCT</span><span class="MsoHyperlink">(First Year) </span></strong></span></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><strong><span style="font-size: 14pt;"><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';">&nbsp;<a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/BPHARMA_BE2YEAR_23082025_0427.pdf" target="_blank" rel="noopener"> </a></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/BPHARMA_BE2YEAR_23082025_0427.pdf" target="_blank" rel="noopener"><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"><span style="font-size: 12pt;">DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span></span><span style="font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase; font-size: 12pt;">/BHMCT</span></a></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/BPHARMA_BE2YEAR_23082025_0427.pdf" target="_blank" rel="noopener"><span class="MsoHyperlink"><span style="font-size: 12pt;">(Second Year) </span></span></a></strong></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/BEDIPLOMA_BPHARMA_23082025_0426.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14pt;"><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';"> </span></span><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"><span style="font-size: 12pt;">DIPLOMA ENGG. (Third Year) /B. E./B. Pharma</span></span><span style="font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase; font-size: 12pt;">/BHMCT</span></span><span class="MsoHyperlink">(Third &amp; Fourth Year)&nbsp;</span></strong></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;"> &nbsp;&nbsp; ACADEMIC CALENDAR FOR THE YEAR 2025-26 (MBBS) </span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/BAMS_23082025_0424.pdf" target="_blank" rel="noopener">ACADEMIC CALENDAR FOR THE YEAR 2025-26 (BAMS)</a> </span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;">ACADEMIC CALENDAR FOR THE YEAR 2025-26 (BHMS-UG) </span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;">ACADEMIC CALENDAR FOR THE YEAR 2025-26 (BHMS -PG) </span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/UTD_23082025_0429.pdf" target="_blank" rel="noopener"><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;">ACADEMIC CALENDAR FOR THE YEAR 2025-26 (UTD)&nbsp;</span></span></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center">&nbsp;</h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center">&nbsp;</h3>

<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><br /><br /></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center">&nbsp;</h3>

<h2 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: center;" align="center"><span style="font-size: 12pt; color: #2dc26b;"><strong><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';"><span style="font-size: 14pt;"><span style="text-decoration: underline;"><span style="color: #e03e2d; font-size: 18pt; text-decoration: underline;">Academic Calendar for the Year 2024-25</span></span></span></span></span></strong></span></h2>

<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;"> &nbsp;&nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/MBBS.pdf" target="_blank" rel="noopener">ACADEMIC CALENDAR FOR THE YEAR 2024-25 (MBBS)&nbsp;</a></span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/BAMS CALENDER.pdf" target="_blank" rel="noopener">ACADEMIC CALENDAR FOR THE YEAR 2024-25 (BAMS)</a> </span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/BHMS UG.pdf" target="_blank" rel="noopener">ACADEMIC CALENDAR FOR THE YEAR 2024-25 (BHMS-UG)</a> </span></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/BHMS PG.pdf" target="_blank" rel="noopener">ACADEMIC CALENDAR FOR THE YEAR 2024-25 (BHMS -PG)</a> </span></span></h3>
<p class="MsoNormal"></p>
<h3 class="MsoNormal" style="margin-bottom: 0pt; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="http://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/ACADEMIC CALENDAR 2024-2025.pdf" target="_blank" rel="noopener"><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;"><span style="font-size: 12pt;">ACADEMIC CALENDAR FOR THE YEAR 2024-25 (UTD)</span></span></a></h3>
<h3 class="MsoNormal"><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"></span></h3>
<h3 class="MsoNormal"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/Academic calender 2024-25.pdf" target="_blank" rel="noopener">Academic Calendar for the year 2024-2025 B.A.B.Ed /B.Ed/B.P.Ed</a></span></h3>
<h3><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"> </span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/Acadmic Calendra for Diploma in Pharmacy 2024-25.pdf" target="_blank" rel="noopener"><span lang="EN-US">ACADEMIC CALENDAR FOR I &amp; II YEAR 2024-25&nbsp;</span> <span lang="EN-US" style="line-height: 115%;">FOR D.PHARMA </span></a></span></h3>
<p><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"> </span></p>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/ACADEMIC CALENDAR OF PARAMEDICAL COURSES FOR SESSION 2024-25.pdf" target="_blank" rel="noopener"><span lang="EN-US" style="line-height: 115%; color: black; background: white;">Paramedical UG/PG/DIPLOMA Course (Yearly System)</span></a></span></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/Academic Calander 2024-25 (SOE).pdf" target="_blank" rel="noopener"><span style="font-size: 12pt;"><strong><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"> DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span><span style="font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase;">/BHMCT</span><span class="MsoHyperlink">(First Year) </span></strong></span></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/ACADEMIC CALENDAR FOR THE FIRST YEAR 2024-25 2year.pdf" target="_blank" rel="noopener"><span style="font-size: 14pt;"><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';">&nbsp; </span></span><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"><span style="font-size: 12pt;">DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span></span><span style="font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase; font-size: 12pt;">/BHMCT</span></span></a><span class="MsoHyperlink"><span style="font-size: 12pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/ACADEMIC CALENDAR FOR THE FIRST YEAR 2024-25 2year.pdf" target="_blank" rel="noopener">(Second Year)</a> </span></span></strong></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/ACADEMIC CALENDAR FOR THE FIRST YEAR 2024-25 3-4 year.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14pt;"><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';"> </span></span><span style="font-family: 'Times New Roman'; color: #241f2a; text-transform: uppercase;"><span style="font-size: 12pt;">DIPLOMA ENGG. (Third Year) /B. E./B. Pharma</span></span><span style="font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8pt; text-transform: uppercase; font-size: 12pt;">/BHMCT</span></span><span class="MsoHyperlink">(Third &amp; Fourth Year) </span></strong></a></h3>
<h3 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: left;" align="center"><span style="font-size: 14pt;"><span class="15"></span></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Academic Calendar 2024-25/Academic calendar 24 (1).pdf" target="_blank" rel="noopener"><span style="text-decoration: underline;"><strong>Academic Calendar for the year 2024-25 (School of Law)</strong></span></a></h3>

<h2 class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: normal; text-align: center;" align="center"><span style="font-size: 12pt; color: #2dc26b;"><strong><span class="MsoHyperlink"><span style="line-height: 115%; font-family: 'Calibri', 'sans-serif';"><span style="font-size: 14pt;"><span style="text-decoration: underline;"><span style="color: #e03e2d; font-size: 18pt; text-decoration: underline;">Academic Calendar for the Year 2023-24</span></span></span></span></span></strong></span></h2>

<p class="MsoNormal"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/UTD.pdf" target="_blank" rel="noopener"><strong>Academic Calendar for Session 2023-24 (Yearly &amp; Semester System) UTD</strong></a></p>
<p class="MsoNormal"><strong style="font-size: 16px;"><span style="color: #006400;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/Paramedical.pdf" target="_blank" rel="noopener">Academic Calendar for All Paramedical 2023-24</a>&nbsp; <br /></span></strong></p>
<p class="MsoNormal"><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/Nursing.pdf" target="_blank" rel="noopener">Academic Calendar for Nursing Session 2023-24 (Yearly &amp; Semester System)</a></strong></p>
<p class="MsoNormal"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/Academic Calendar 2023-24 (01)_LAW.pdf" target="_blank" rel="noopener"><span style="text-decoration: underline;"><strong>Academic Calendar for the year 2023-24 (School of Law)</strong></span></a></p>
<p class="MsoNormal"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/Academic Calendar 2023-24 bed babed.pdf" target="_blank" rel="noopener"><strong>Academic Calendar for the year 2023-24 (Semester System B.A.B.Ed/ B.Ed/B.P.Ed)</strong></a></p>
<p class="MsoNormal"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/FIRST YEAR .pdf" target="_blank" rel="noopener"><strong><span class="MsoHyperlink"><span style="font-size: 11.0pt;  line-height: 115%; font-family: 'Calibri','sans-serif';        ">Academic Calendar for the Year 2023-24 </span></span><span style=" font-family: 'Times New Roman'; color: #241f2a;  text-transform: uppercase; font-size: 10.0000pt;">&nbsp;DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span><span style=" font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8000pt;  text-transform: uppercase; font-size: 10.0000pt;">/BHMCT</span><span class="MsoHyperlink">(First Year) </span></strong></a></p>
<p class="MsoNormal"><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/Eng.pdf" target="_blank" rel="noopener"><span class="MsoHyperlink"><span style="font-size: 11.0pt;  line-height: 115%; font-family: 'Calibri','sans-serif';        ">Academic Calendar for the Year 2023-24 </span></span><span style=" font-family: 'Times New Roman'; color: #241f2a;  text-transform: uppercase; font-size: 10.0000pt;">&nbsp;DIPLOMA ENGG./B. E./M.TECH/MCA/MBA/M. Pharma/B. Pharma</span><span style=" font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8000pt;  text-transform: uppercase; font-size: 10.0000pt;">/BHMCT</span><span class="MsoHyperlink">(Second Year) </span></a></strong></p>
<p class="MsoNormal"><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/Academic Calendar 2023-24 (01)_6.pdf" target="_blank" rel="noopener"><span class="MsoHyperlink"><span style="font-size: 11.0pt;  line-height: 115%; font-family: 'Calibri','sans-serif';        ">Academic Calendar for the Year 2023-24 </span></span><span style=" font-family: 'Times New Roman'; color: #241f2a;  text-transform: uppercase; font-size: 10.0000pt;">&nbsp;DIPLOMA ENGG. (Third Year) /B. E./B. Pharma</span><span style=" font-family: 'Times New Roman'; color: #110d14; letter-spacing: 1.8000pt;  text-transform: uppercase; font-size: 10.0000pt;">/BHMCT</span><span class="MsoHyperlink">(Third &amp; Fourth Year) </span></a></strong></p>
<p class="MsoNormal"><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/School of Homoeopathy.pdf" target="_blank" rel="noopener"><span style="text-decoration: underline;">Academic Calendar for the year 2022-23 (School of Homoeopathy)</span></a></strong></p>
<p class="MsoNormal"><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/2023-24/BAMS.pdf" target="_blank" rel="noopener">Academic Calendar B.A.M.S. First Year 2023 - 24 (18 Months )&nbsp;</a></strong></p>

<p class="MsoNormal"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IMG_0001_16022023_0256.pdf" target="_blank" rel="noopener"><span class="MsoHyperlink"><span style="font-size: 11.0pt;  line-height: 115%; font-family: 'Calibri','sans-serif';        ">Academic Calendar for the Year 2022-2023 Bachelor of Engg. Diploma/UG/PG/MBA/MCA/BHMCT </span>(First &amp; Second Semester) </span></a></p>
<p class="MsoNormal"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IMG_16022023_0253.pdf" target="_blank" rel="noopener">Academic Calendar for the year 2022-2023 Pharmacy UG and PG Semester system <span class="MsoHyperlink">(First &amp; Second Semester) </span></a></p>
<p><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IMG_16022023_0253.pdf" target="_blank" rel="noopener"> </a><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/Yearly System.pdf" target="_blank" rel="noopener">Academic Calendar for Session 2022-23 (Yearly System-I, II &amp; III Year)&nbsp;&nbsp;</a></p>
<p><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/All UG PG Diploma Semester.pdf" target="_blank" rel="noopener">Academic Calendar for the year 2022-23 (Semester System All UG, PG &amp; Diploma (Engg.)- III Semester Onward)&nbsp;</a></p>
<p><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/B.A.B.ED B.P.ED Semester.pdf" target="_blank" rel="noopener">Academic Calendar for the year 2022-23 (Semester System B.A.B.Ed/ B.Ed/B.P.Ed)</a></p>
<p><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/B.A.M.S..pdf" target="_blank" rel="noopener">Academic Calendar B.A.M.S. First Year 2021-22 to 2023 (18 Months )&nbsp;</a></p>
<p><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/PG Yearly.pdf" target="_blank" rel="noopener">Academic Calendar <span style="text-decoration: underline;">for the Year 2022-23 (Post Graduate Course)</span></a><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/School of Homoeopathy.pdf" target="_blank" rel="noopener"><span style="text-decoration: underline;">&nbsp; </span></a></p>
<p><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Academic/acdmic calendar bams 2022-23.pdf" target="_blank" rel="noopener">Academic Calendar B.A.M.S. First Year 2022 - 23 (18 Months )&nbsp;</a></strong></p>
<p><strong style="font-size: 16px;"><span style="color: #006400;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/2019-20_AC/Academic_Calender_for_Yearly_Paramedical_2019-20.pdf" target="_blank" rel="noopener">Academic Calendar for All Paramedical 2019-20</a>&nbsp;&nbsp;</span></strong></p>

</div>
        </div>
      </div>

      <!-- Sticky Category Sidebar (Right) -->
      <div class="col-lg-4 col-xl-3 sticky-top" style="top: 20px; z-index: 10;">
        <?php require_once __DIR__ . '/../includes/sidebar.php'; ?>
      </div>

    </div>
  </div>
</section>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>