<?php
$page_title = 'CriteriaFour - SSSUTMS';
$banner_title = 'CriteriaFour';
$banner_category = 'Academic';

require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/header.php';
require_once __DIR__ . '/../../includes/topbar.php';
require_once __DIR__ . '/../../includes/navbar.php';
require_once __DIR__ . '/../../includes/page-banner.php';
?>

<section class="subpage-main-section py-4 bg-light">
  <div class="container-fluid px-lg-5">
    <div class="row g-4 align-items-start">
      
      <!-- Main Content Area (Left) -->
      <div class="col-lg-8 col-xl-9">
        <div class="content-card">
          <div class="content-card-body">
            <p><span style="text-decoration: underline;"><strong>Criteria 4</strong></span></p>

<p class="MsoNormal"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">4.1.1</span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">&nbsp; &nbsp; Physical Facilites&nbsp;&nbsp; </span></p>
<p><span style="font-size: 12.0pt;  line-height: 115%; font-family: Symbol;   "><span style=""><span style="font: 7.0pt 'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span></span></span><strong></span></span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: Symbol;   "><span style=""><span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  ">Facilities for Teaching - Learning</span></p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; <span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/sssutms.pdf" target="_blank" rel="noopener"><span style="color: windowtext;">Click here</span></a></span></p>
<p class="MsoNormal"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  ">4.1.2</span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="">&nbsp; </span><span style="">&nbsp;</span>Facilities for Cultural Activities, Yoga, Games and Sports <br /><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.1.2/4.1.2.pdf" target="_blank" rel="noopener"><span style="color: windowtext;">Click here</span></a></span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">&nbsp;</span><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">4.1.3</span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; "> &nbsp; General Campus Facilities&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.1.2/4.1.3.pdf" target="_blank" rel="noopener"><span style="color: windowtext;">Click here</span></a></span></p>
<p class="MsoNormal"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">4.1.4</span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">&nbsp; <span style="">&nbsp;</span>CA Certificate &amp; Audited Income and Expenditure Statement&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 288.0pt;"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; "><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; </span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/final audit.pdf" target="_blank" rel="noopener">Click here</a></span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; line-height: 12.65pt; background: white;"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">4.2&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><span style="font-size: 11.0pt; font-family: 'Book Antiqua','serif'; color: black; text-transform: uppercase;">Number of seats earmarked for reserved category as per&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span style="font-size: 11.0pt; font-family: 'Book Antiqua','serif'; color: black; text-transform: uppercase;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; line-height: 12.65pt; background: white;"><span style="font-size: 11.0pt; font-family: 'Book Antiqua','serif'; color: black; text-transform: uppercase;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GOI/State Govt. Rule year-wise during last five year&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-size: 11.0pt; font-family: 'Book Antiqua','serif'; color: black; text-transform: uppercase;"> </span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.2/4.2.pdf" target="_blank" rel="noopener"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">Click here</span></a></p>

<p class="MsoNormal"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">4.2.1</span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; ">&nbsp;&nbsp; Library as a Learning Resource &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="">&nbsp; &nbsp; &nbsp;&nbsp; </span></span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif'; "><span style="">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;</span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp; </span><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/LIBRARY AS A LEARNING RESOURESE.pdf" target="_blank" rel="noopener"><span style="color: windowtext;">Click here</span></a></span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="color: windowtext;"><strong>4.2.2</strong> &nbsp; Institution has subscription for e-Library resources&nbsp;&nbsp;&nbsp;</span></span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="color: windowtext;">&nbsp;</span></span><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="color: windowtext;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.2.2/4.2.2 UPLOD.pdf" target="_blank" rel="noopener"><span style="text-decoration: underline;">Click here</span></a></span></span></p>
<p class="MsoNormal"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  ">4.3.1</span></strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style=""> &nbsp; </span></span><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  ">Percentage of classrooms and seminar halls with ICT - enabled </span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; facilities&nbsp; such as&nbsp; LCD, smart board, Wi-Fi/LAN, audio video </span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; recording facilities .(Data only for the latest completed academic year)&nbsp;&nbsp; <br style="" /></span><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong> </strong></span><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/Criteria 4.3.1.pdf" target="_blank" rel="noopener"><span style="color: windowtext;">Click here</span></a></strong></span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><strong><span style="color: windowtext;">4.3.2&nbsp;</span></strong><span style="color: windowtext;"> &nbsp;&nbsp; IT Services Policy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="color: windowtext;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.3.2/4.3.2_1682157313_9437.pdf" target="_blank" rel="noopener"><strong>Click here</strong></a></span></span></p>
<p class="MsoNormal" style="text-align: left;"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="color: windowtext;">4.3.3&nbsp;&nbsp; </span></span></strong><span style="font-family: Calibri; font-size: 14pt;">Summary of Computer Distribution , Declaration Certificate, Computer Invoices</span></p>
<p class="MsoNormal" style="text-align: left;"><span style="font-family: Calibri; font-size: 14pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong> <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.3.3/computer distribution and bill.pdf" target="_blank" rel="noopener">Click here</a></strong></span></p>
<p class="MsoNormal" style="text-align: left;"><strong><span style="font-size: 12.0pt;  line-height: 115%; font-family: 'Bookman Old Style','serif';  "><span style="color: windowtext;">4.3.4&nbsp;&nbsp; </span></span></strong><span style=" font-family: Calibri;  font-size: 14.0000pt;">Available bandwidth of internet connection in the Institution </span></p>
<p class="MsoNormal" style="text-align: left;"><span style=" font-family: Calibri;  font-size: 14.0000pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.3.4/4.3.4.pdf" target="_blank" rel="noopener"><strong>Click here</strong></a></span></p>
<p class="MsoNormal" style=" text-align: left;"><strong>4.3.5</strong>&nbsp;&nbsp;&nbsp; <span style=" font-family: Calibri;  font-size: 14.0000pt; ">Institution has the following Facilities </span><span style=" font-family: Calibri;  font-size: 14.0000pt; ">for e-content development </span></p>
<p class="MsoNormal" style=" text-align: left;"><span style=" font-family: Calibri;  font-size: 14.0000pt; ">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.3.5/4.3.5 .pdf" target="_blank" rel="noopener"><strong>Click here</strong></a></span></p>
<p class="MsoNormal" style="text-indent: 0.0000pt; padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff; margin: 0.0000pt;"><span style=" font-family: Calibri;  font-size: 14.0000pt; "><strong>4.4.2&nbsp;&nbsp;&nbsp; </strong></span><span style=" font-family: Calibri;   color: #000000; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 12.0000pt;  background: #ffffff; ">Maintenance policy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p class="MsoNormal" style="text-indent: 0.0000pt; padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff; margin: 0.0000pt;"><span style=" font-family: Calibri;   color: #000000; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 12.0000pt;  background: #ffffff; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; <strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 4/4.4.2/4.4.2_1682159880_9437.pdf" target="_blank" rel="noopener">Click here</a></strong></span></p>

          </div>
        </div>
      </div>

      <!-- Sticky Category Sidebar (Right) -->
      <div class="col-lg-4 col-xl-3 sticky-top" style="top: 20px; z-index: 10;">
        <?php require_once __DIR__ . '/../../includes/sidebar.php'; ?>
      </div>

    </div>
  </div>
</section>

<?php require_once __DIR__ . '/../../includes/footer.php'; ?>