<?php
$page_title = 'CriteriaTwo - SSSUTMS';
$banner_title = 'CriteriaTwo';
$banner_category = 'Academic';

require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/header.php';
require_once __DIR__ . '/../../includes/topbar.php';
require_once __DIR__ . '/../../includes/navbar.php';
require_once __DIR__ . '/../../includes/page-banner.php';
?>

<section class="subpage-main-section py-4 bg-light">
  <div class="container-fluid px-lg-5">
    <div class="row g-4 align-items-start">
      
      <!-- Main Content Area (Left) -->
      <div class="col-lg-8 col-xl-9">
        <div class="content-card">
          <div class="content-card-body">
            <p><span style="text-decoration: underline;"><span style="color: #2dc26b; text-decoration: underline;">Criteria 2</span></span></p>

<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"><strong><span style=" font-family: 'Times New Roman';   color: #085294; font-weight: bold; font-size: 14.0000pt; "><span style="color: #000000;"><span style="color: #3598db;">2.2.1</span> </span></span></strong><strong><span style=" font-family: 'Times New Roman';   color: #085294; font-weight: bold; font-size: 14.0000pt; ">&nbsp;&nbsp;&nbsp; </span></strong><span style="font-family: 'Times New Roman'; color: #085294; font-size: 14pt;"><span style="color: #000000;">The institution assesses the learning levels of</span></span><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">the students and organises special</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">Programmes</span></span></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; for advanced learners&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;"> and&nbsp; slow</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">learners</span></span></p>
<p class="MsoNormal" style="margin-top: 0pt; margin-right: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 0pt 560px; text-align: left; vertical-align: baseline; background: #ffffff;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 2/combined 2.2.1 final.pdf" target="_blank" rel="noopener"><strong><span style=" font-family: 'Times New Roman';   color: #085294; font-weight: bold; font-size: 14.0000pt; "><span style="color: #1913b0;">Click here</span></span></strong></a></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"><strong><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;"><span style="color: #3598db;">2.3.1&nbsp;</span>&nbsp;&nbsp; </span></span></strong><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;">Student centric methods, such as</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">experiential learning, participative learning</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">and problem solving</span></span></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; methodologies are used</span><span style="font-family: 'Times New Roman'; font-size: 14pt;"> </span><span style="font-family: 'Times New Roman'; font-size: 14pt;">for enhancing learning experiences</span></span></p>
<p class="MsoNormal" style="margin-top: 0pt; margin-right: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 0pt 560px; text-align: left; vertical-align: baseline; background: #ffffff;"><span style="color: #1913b0;">&nbsp;<a style="color: #1913b0;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 2/combined 2.3.1 final.pdf" target="_blank" rel="noopener"><strong><span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 14pt;">Click here</span></strong></a></span></p>
<p class="MsoNormal" style="  text-indent: -7.0000pt;  padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff; margin: 0.0000pt 0.0000pt 0.0000pt 7.0000pt;"><span style="color: #000000;"><strong><span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 14pt;"><span style="color: #3598db;">2.3.2</span>&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><span style="font-family: 'Times New Roman'; font-size: 14pt;">Teachers use ICT enabled tools including</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">online resources for effective teaching and</span></span></p>
<p class="MsoNormal" style="  text-indent: -7.0000pt;  padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff; margin: 0.0000pt 0.0000pt 0.0000pt 7.0000pt;"><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span style="font-family: 'Times New Roman'; font-size: 14pt;">learning process.</span></span></p>
<p class="MsoNormal" style="text-indent: -7pt; padding: 0pt 0pt 0pt 560px; text-align: left; vertical-align: baseline; background: #ffffff; margin: 0pt 0pt 0pt 7pt;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 2/combined 2.3.2 final.pdf" target="_blank" rel="noopener"><strong><span style=" font-family: 'Times New Roman';   color: #085294; font-weight: bold; font-size: 14.0000pt; "><span style="color: #1913b0;">&nbsp;Click here</span></span></strong></a></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"><span style="color: #000000;"><strong><span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 14pt;"><span style="color: #3598db;">2.3.3</span>&nbsp;&nbsp; </span></strong><span style="font-family: 'Times New Roman'; font-size: 14pt;">Ratio of students to mentor for academic</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">and other related issues</span></span></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"><span style="color: #000000;"><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (Data for the latest</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">&nbsp;</span><span style="font-family: 'Times New Roman'; font-size: 14pt;">completed academic year )</span></span></p>
<p class="MsoNormal" style="margin-top: 0pt; margin-right: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 0pt 560px; text-align: left; vertical-align: baseline; background: #ffffff;"><strong><span style=" font-family: 'Times New Roman';   color: #085294; font-weight: bold; font-size: 14.0000pt; ">&nbsp;<span style="color: #1913b0;"> <a style="color: #1913b0;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 2/combined 2.3.3 final.pdf" target="_blank" rel="noopener">Click here</a></span></span></strong></p>
<p class="MsoNormal" style=" text-align: left; line-height: 114%; margin: 0.0000pt 0.0000pt 10.0000pt 0.0000pt;"><span style="color: #000000;"><strong><span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 14pt;"><span style="color: #3598db;">2.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong></span><span style=" font-family: SimSun;    line-height: 114%; color: #000000; font-size: 14.0000pt;"><span style="font-family: Calibri;">Number of revaluation applications year wise</span></span></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;"></p>
<p class="MsoNormal" style="margin-top: 0.0000pt; margin-right: 0.0000pt; margin-bottom: 0.0000pt;   padding: 0pt 0pt 0pt 0pt;  text-align: left; vertical-align: baseline; background: #ffffff;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; <strong><span style=" font-family: 'Times New Roman';   color: #085294; font-weight: bold; font-size: 14.0000pt; "><span style="color: #1913b0;"> <a style="color: #1913b0;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/IQAC/NAAC/Criteria 2/combined revalution.pdf" target="_blank" rel="noopener">Click here</a></span></span></strong></p>

          </div>
        </div>
      </div>

      <!-- Sticky Category Sidebar (Right) -->
      <div class="col-lg-4 col-xl-3 sticky-top" style="top: 20px; z-index: 10;">
        <?php require_once __DIR__ . '/../../includes/sidebar.php'; ?>
      </div>

    </div>
  </div>
</section>

<?php require_once __DIR__ . '/../../includes/footer.php'; ?>