<?php
$page_title = 'E-Content - SSSUTMS';
$banner_title = 'E-Content';
$banner_category = 'Download';

require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/topbar.php';
require_once __DIR__ . '/../includes/navbar.php';
require_once __DIR__ . '/../includes/page-banner.php';
?>

<section class="subpage-main-section py-4 bg-light">
  <div class="container-fluid px-lg-5">
    <div class="row g-4 align-items-start">
      
      <!-- Main Content Area (Left) -->
      <div class="col-lg-8 col-xl-9">
        <div class="content-card">
          <div class="content-card-body">
            <div style=" border: none; border-bottom: solid #002B5B 1.0pt;  padding: 0cm 0cm 8.0pt 0cm;">
<p class="MsoNormal" style="text-align: center;"><span style="text-decoration: underline;"><span style="font-family: 'arial black', sans-serif; color: #e67e23; text-decoration: underline;"><strong><span style="font-size: 14pt; line-height: 115%;">SSSUTMS e-Knowledge </span></strong></span></span></p>

<p class="MsoNormal" style="text-align: left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
<p class="MsoNormal"><strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Goudy Old Style','serif';  color: #085294;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</span></strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Goudy Old Style','serif';  color: #085294;"> -&nbsp;</span><strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Goudy Old Style','serif';  color: #085294;"> <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 6 Issue 2 16 to 30 November 2023.pdf" target="_blank" rel="noopener">Vol 6 Issue 2 16 to 30 November 2023</a> </span></strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 1 Issue 2 16 to 30 June 2023.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif';  "><img src="../../../../registration.telangana.gov.in/resources/img/new.gif" alt=""  height="29" /></span></strong></a></p>
<p class="MsoNormal"><strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Goudy Old Style','serif';  color: #085294;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; - </span></strong><strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Goudy Old Style','serif';  color: #085294;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 6 Issue 1 01 to 15 November 2023.pdf" target="_blank" rel="noopener">Vol 6 Issue 1 01 to 15 November 2023</a>&nbsp; </span></strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;"><strong> </strong></p>
<p class="MsoNormal" style="text-align: left;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - &nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/elarning_opt.pdf" target="_blank" rel="noopener">Vol 5 Issue 2 16 to 31 October 2023 </a></strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>- &nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowledge/SSSUTMS Vol 5 Issue 1 01 to 15 October 2023.pdf" target="_blank" rel="noopener">Vol 5 Issue 1 01 to 15 October 2023</a> </strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>-</strong>&nbsp;&nbsp;&nbsp;<a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 4 Issue 2 16 to 30 Sep 2023.pdf" target="_blank" rel="noopener"> <span style="font-family: 'arial black', sans-serif;">Vol 4 Issue 2 16 to 30 Sep 2023</span> </a><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;"><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -&nbsp; &nbsp;&nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 4 Issue 1 01 to 15 September 2023.pdf" target="_blank" rel="noopener">Vol 4 Issue 1 01 to 15 September 2023</a> &nbsp;</strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left; padding-left: 40px;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&nbsp; &nbsp;&nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 3 Issue 2 01 to 15 August 2023.pdf" target="_blank" rel="noopener">Vol 3 Issue 2 16 to 31 August 2023</a>&nbsp;&nbsp; </strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; <strong>&nbsp; &nbsp;&nbsp; - &nbsp;&nbsp;</strong> &nbsp; <strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 3 Issue 1 01 to 15 August 2023.pdf" target="_blank" rel="noopener">Vol 3 Issue 1 01 to 15 August 2023 </a></strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;"><span style="font-size: 12pt; font-family: 'comic sans ms', sans-serif;"><span style="line-height: 115%;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&nbsp; </strong></span></span><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 2 Issue 2 16 to 31 July 2023.pdf" target="_blank" rel="noopener"> Vol 2 Issue 2 16 to 31 July 2023 &nbsp; &nbsp; &nbsp;&nbsp; </a></strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal" style="text-align: left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; <span style="font-size: 12pt; font-family: 'comic sans ms', sans-serif;"><span style="line-height: 115%;"><strong>-</strong></span></span><strong> &nbsp; &nbsp; <a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 2 Issue 1 01 to 15 July 2023.pdf" target="_blank" rel="noopener">Vol 02/ Issue 1/ 01 -15 July 2023&nbsp;</a> </strong><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal"><strong><span style="font-size: 14pt; line-height: 115%;">&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; </span></strong><span style="font-size: 12pt; font-family: 'comic sans ms', sans-serif;"><span style="line-height: 115%;">&nbsp;&nbsp;&nbsp;&nbsp; <strong>- &nbsp;</strong> &nbsp;<a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS Vol 1 Issue 2 16 to 30 June 2023.pdf" target="_blank" rel="noopener">Vol.01/Issue 02/16-30 June2023&nbsp;&nbsp;</a> </span></span><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif" height="30" /></a></p>
<p class="MsoNormal"><strong><span style="font-size: 14pt; line-height: 115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span style="font-family: 'comic sans ms', sans-serif;"> - &nbsp; </span></span></strong><span style="font-family: 'comic sans ms', sans-serif;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><span style="font-size: 12pt;"><span style="line-height: 115%;">Vol.01/Issue 1/1-15 June2023 &nbsp; &nbsp; </span></span></a></span><a style="box-sizing: border-box; background-color: transparent; color: #000000; text-decoration: none; -webkit-font-smoothing: antialiased; outline: 0px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;" href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e-knowldege/SSSUTMS (1).pdf" target="_blank" rel="noopener"><img style="box-sizing: border-box; border: none; vertical-align: middle; max-width: 100%;" src="<?php echo BASE_URL; ?>assets/images/click-here.gif"  height="33" /></a></p>

<p class="MsoNormal" style="margin-bottom: 22.5pt; line-height: normal; padding: 0cm; text-align: center;"><span style="text-decoration: underline;"><span style="font-family: 'arial black', sans-serif; color: #e67e23; text-decoration: underline;"><strong><span style="font-size: 14pt; line-height: 115%;">SSSUTMS e-Report </span></strong></span></span></p>
<p class="MsoNormal" style="margin-bottom: 22.5pt; line-height: normal; padding: 0cm 0cm 0cm 80px; text-align: left;"><span style="font-family: 'arial black', sans-serif; color: #e67e23;"><strong><span style="font-size: 14pt; line-height: 115%;"> </span></strong></span></span><strong></strong></p>

<p class="MsoNormal" style="margin-bottom: 22.5pt; line-height: normal; padding: 0cm; text-align: center;"><u style="font-size: 0.875rem;"><span style="font-size: 21pt; font-family: 'Times New Roman', serif; color: #9c0000;">Students Forum</span></u></p>

<p class="MsoNormal" style="margin-bottom: 22.5pt; line-height: normal; padding: 0cm; text-align: left;"></span></span><u></u><span style="font-size: 0.875rem; color: #003163;">&nbsp; </span><span style="font-weight: bolder;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #003163;"><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/Download/Preamble 2.pdf" target="_blank" rel="noopener">Cultural and Technical </a></span></span></p>
<p class="MsoNormal" style="margin-bottom: 22.5pt; text-align: center; line-height: normal; border: none; padding: 0cm;"><u style="font-size: 0.875rem;"><span style="font-size: 21pt; font-family: 'Times New Roman', serif; color: #9c0000;">Online Study Material for Students</span></u></p>
<p class="MsoNormal" style="margin-bottom: 22.5pt; line-height: normal; padding: 0cm; text-align: left;"></p>

<p class="MsoListParagraphCxSpFirst" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: blue; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/definitionandtypesofresearch-100801181630-phpapp02.pdf" target="_blank" rel="noopener"><span style="color: blue;">Research Methodology</span></a></span></strong></p>
<p class="MsoListParagraphCxSpFirst" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/definitionandtypesofresearch-100801181630-phpapp02.pdf" target="_blank" rel="noopener"></a><strong><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/research Report.pdf" target="_blank" rel="noopener">Research Report Writing</a></strong></p>
<p class="MsoListParagraphCxSpFirst" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/SURVEY.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: blue; "><span style="color: blue;">Survey&nbsp; Research</span></span></strong></a></p>
<p class="MsoListParagraphCxSpFirst" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><span style="font-size: 12.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/Women.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14.0pt; line-height: 200%; color: blue;">Women in Sports</span></strong></a></span></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%; "></span></span><span style="font-size: 12.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/3- Physical Fitness.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14.0pt; line-height: 200%; color: blue;">Physical Fitness</span></strong></a></span></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%; "></span></span><strong><u><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: blue; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/Hypotheses PPT.pdf" target="_blank" rel="noopener"><span style="color: blue;">Hypotheses</span></a></span></u></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><span style="font-size: 12.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/SOURCES_OF_INVALIDITY12.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14.0pt; line-height: 200%; color: blue;">SOURCES OF INVALIDITY</span></strong></a></span></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><span style="font-size: 12.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/SAMPLING.pdf" target="_blank" rel="noopener"><strong><span style="font-size: 14.0pt; line-height: 200%; color: blue;">SAMPLING</span></strong></a><a href="ftp://sssutms_upload@unikcore.24mycloud.com:51503/Link/e content/SAMPLING.pdf" target="_blank" rel="noopener"><span style="color: blue;"> </span></a></span></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: blue; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/e content/Components of Fitness %26 Tests TO GO ON.pdf" target="_blank" rel="noopener"><span style="color: blue;">Components of Fitness </span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/ANATOMY_PHYSIOLOGY.pdf" target="_blank" rel="noopener"><span style="color: blue;">Notes on Anatomy and Physiology</span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Foundation_physical_edcation.pdf" target="_blank" rel="noopener"><span style="color: blue;">Notes on History, Principles &amp; Foundation of Physical Education</span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><span style="font-size: 12.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; ">&nbsp;</span><u><span style="font-size: 10.5pt; line-height: 200%; font-family: 'Arial','sans-serif';  color: blue; "> </span></u><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Complete Guide to Sports Training.pdf" target="_blank" rel="noopener"><span style="color: blue;">Online Complete Guide to Sports Training</span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Computer  System Architecture.pdf" target="_blank" rel="noopener"><span style="color: blue;">Online Notes on Computer System Architecture</span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Digital electronics.pdf" target="_blank" rel="noopener"><span style="color: blue;">Online Notes on Digital electronics</span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/RCC.pdf" target="_blank" rel="noopener"><span style="color: blue;">Online Noes Structural Design &amp; Drawing-I (RCC)</span></a></span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Building Material.pdf" target="_blank" rel="noopener"><span style="color: blue;">Online Notes on Building Material</span></a></span></strong></p>
<p class="MsoListParagraphCxSpLast" style=" margin-bottom: .0001pt; margin-left: 54.0pt;  text-indent: -18.0pt; line-height: 200%;  tab-stops: list 36.0pt;"></span></span><strong><span style="font-size: 14.0pt; line-height: 200%; font-family: 'Times New Roman','serif';  color: #003163; "><a href="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/BOOK - SPRITUAL MANAGEMENT.pdf" target="_blank" rel="noopener"><span style="color: blue;">SPRITUAL MANAGEMENT</span></a></span></strong></p>

<p class="MsoNormal" style="line-height: normal;"><span style="font-weight: bolder; font-size: 0.875rem;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #003163;">Video Lecturer&nbsp;</span></span></p>
<p class="MsoNormal" style="line-height: normal;"><video class="note-video-clip" src="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Prabhakar-FINAL.mp4,https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Brijesh-FINAL.mp4" controls="controls"  height="210"></video><video class="note-video-clip" src="https://www.sssutms.co.in/cms/Areas/Website/Files/Link/EContent/Prabhakar-FINAL.mp4" controls="controls"  height="210"></video><span style="font-weight: bolder; font-size: 0.875rem;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #003163;"><br /></span></span></p>
<p class="MsoNormal" style="line-height: normal;"><span style="font-weight: bolder; font-size: 0.875rem;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #003163;">&nbsp;</span></span></p>
</div>
          </div>
        </div>
      </div>

      <!-- Sticky Category Sidebar (Right) -->
      <div class="col-lg-4 col-xl-3 sticky-top" style="top: 20px; z-index: 10;">
        <?php require_once __DIR__ . '/../includes/sidebar.php'; ?>
      </div>

    </div>
  </div>
</section>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>